### ISSUE TITLE
Ninja Forms Jqmigrate conflict

### ISSUE THREAD

**Issue by leavreality** [godaddy/wp-escapade-theme#75] opened 2019-04-27 12:52 UTC
Hi on my site build in and hosted by GoDaddy using this theme with Ninja Forms, they no longer work, tried to fix the problem thought it might be a plugin conflict but it seem to be the theme, it JQMigrate 1.4.1 jquery that seems to be causing the error. I'm not much of a web developers (why I use wordpress) so any help or advice would be helpful.
the site it happing on. 
http://carekindtraining.co.uk/

**Comment by EvanHerman** [comment] 2019-07-17 15:49
@leavreality 

It looks like you were able to get this resolved (or maybe you stopped using Ninja Forms). I'm going to close this issue out as I haven't been able to reproduce it and I'm not seeing the issue on your live site.

Evan

**Closed by EvanHerman** 2019-07-17 15:49 UTC
